version: '3.4'

services:
  ferramentaria-postgres:
    image: postgres:13-alpine
    container_name: ferramentaria-postgres
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=Ferramentaria
    ports:
      - 5432:5432
    restart: always

  ferramentaria-api:
    build: .
    container_name: ferramentaria-api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ConnectionStrings:PostgreSQL=Server=ferramentaria-postgres;Port=5432;Database=Ferramentaria;User Id=admin;Password=123456"
    ports:
      - 8000:80
    depends_on:
      - ferramentaria-postgres
    restart: always

  ferramentaria-pgadmin:
    image: dpage/pgadmin4
    container_name: ferramentaria-pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@ferramentaria.com
      - PGADMIN_DEFAULT_PASSWORD=admin1234
    restart: always
    ports:
        - 5050:80
