version: '3.4'

services:
  ferramentaria-postgres:
    image: postgres:13-alpine
    container_name: ferramentaria-postgres
    environment:
      - POSTGRES_USER=ferramentaria
      - POSTGRES_PASSWORD=Univesp2021!
      - POSTGRES_DB=Ferramentaria
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/data/db
    restart: on-failure

volumes:
  postgres-data:
